version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677

